<a href="https://colab.research.google.com/github/AbrarAli-SE/Code-a-Ai/blob/main/Lab_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Name: **Abrar Ali**
# SAP ID: **55843**

In [2]:
import numpy as np

matrix = np.arange(2, 11).reshape(3, 3)

float_matrix = matrix.astype(float)

flattened = float_matrix.flatten()
max_val = np.max(flattened)
min_val = np.min(flattened)

print("Original Matrix:\n", float_matrix)
print("Flattened Array:", flattened)
print("Maximum Value:", max_val)
print("Minimum Value:", min_val)


Original Matrix:
 [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
Flattened Array: [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
Maximum Value: 10.0
Minimum Value: 2.0
