<a href="https://colab.research.google.com/github/AbrarAli-SE/Code-a-Ai/blob/main/Lab_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Name: **Abrar Ali**
# SAP ID: **55843**
# lab 06

## Task 01

In [ ]:
import numpy as np

# 🔧 Converts puzzle list to coordinate form
def coordinates(puzzle):
    return {val: (i // 3, i % 3) for i, val in enumerate(puzzle)}

# 🧠 Heuristic: Misplaced Tiles
def misplaced_tiles(current_coords, goal_coords):
    return sum(1 for tile in current_coords if tile != 0 and current_coords[tile] != goal_coords[tile])

# 🚀 A* Evaluation Function (Simplified for Misplaced Tile Count)
def evaluate_misplaced(puzzle, goal):
    current_coords = coordinates(puzzle)
    goal_coords = coordinates(goal)
    misplaced = misplaced_tiles(current_coords, goal_coords)
    print("Puzzle State:")
    print(np.array(puzzle).reshape(3, 3))
    print("Goal State:")
    print(np.array(goal).reshape(3, 3))
    print(f"Misplaced Tiles Heuristic: {misplaced}\n")
    return misplaced

# ------------------ 🔹 ORIGINAL VALUES ------------------
print("🔹 ORIGINAL CONFIGURATION")
original_puzzle = [2, 8, 3,
                   1, 6, 4,
                   7, 0, 5]

original_goal = [1, 2, 3,
                 8, 0, 4,
                 7, 6, 5]

evaluate_misplaced(original_puzzle, original_goal)

# ------------------ 🔸 UPDATED VALUES ------------------
print("🔸 UPDATED CONFIGURATION")
updated_puzzle = [1, 2, 3,
                  4, 0, 6,
                  7, 5, 8]

updated_goal = [1, 2, 3,
                4, 5, 6,
                7, 8, 0]

evaluate_misplaced(updated_puzzle, updated_goal)

🔹 ORIGINAL CONFIGURATION
Puzzle State:
[[2 8 3]
 [1 6 4]
 [7 0 5]]
Goal State:
[[1 2 3]
 [8 0 4]
 [7 6 5]]
Misplaced Tiles Heuristic: 4

🔸 UPDATED CONFIGURATION
Puzzle State:
[[1 2 3]
 [4 0 6]
 [7 5 8]]
Goal State:
[[1 2 3]
 [4 5 6]
 [7 8 0]]
Misplaced Tiles Heuristic: 2



2

## 🔍 A* Search Heuristic Analysis – Misplaced Tiles

This code demonstrates the use of the **Misplaced Tiles heuristic** to evaluate how far a given puzzle configuration is from its goal state. It is a simplified version of the A* search algorithm, focusing only on the heuristic calculation.

### 🧠 Heuristic Used
- **Misplaced Tiles**: Counts how many tiles are not in their correct position compared to the goal.
- This heuristic is admissible and easy to compute, making it suitable for basic puzzle-solving strategies.

### 🔹 Original Configuration
- **Initial Puzzle**: `[2, 8, 3, 1, 6, 4, 7, 0, 5]`
- **Goal State**: `[1, 2, 3, 8, 0, 4, 7, 6, 5]`
- **Misplaced Tiles**: The output shows how many tiles are incorrectly placed, helping estimate the cost to reach the goal.

### 🔸 Updated Configuration
- **Initial Puzzle**: `[1, 2, 3, 4, 0, 6, 7, 5, 8]`
- **Goal State**: `[1, 2, 3, 4, 5, 6, 7, 8, 0]`
- This configuration is closer to the goal, and the heuristic reflects that with a lower misplaced tile count.

### ✅ Purpose
- This evaluation helps us understand how the heuristic behaves with different puzzle states.
- It lays the foundation for implementing full A* search, where this heuristic would guide the selection of the next best move.


## Task 02

In [5]:
import heapq

# 🧠 Heuristic: Manhattan Distance
def heuristic(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1])

# 🚀 A* Search Algorithm
def astar(grid, start, goal):
    rows, cols = len(grid), len(grid[0])
    open_set = []
    heapq.heappush(open_set, (0, start))
    came_from = {}
    g_score = {start: 0}

    while open_set:
        _, current = heapq.heappop(open_set)

        if current == goal:
            path = []
            while current in came_from:
                path.append(current)
                current = came_from[current]
            path.append(start)
            return path[::-1]

        for dx, dy in [(0,1), (1,0), (0,-1), (-1,0)]:
            neighbor = (current[0]+dx, current[1]+dy)
            if 0 <= neighbor[0] < rows and 0 <= neighbor[1] < cols:
                if grid[neighbor[0]][neighbor[1]] == 1:  # obstacle
                    continue
                tentative_g = g_score[current] + 1
                if neighbor not in g_score or tentative_g < g_score[neighbor]:
                    g_score[neighbor] = tentative_g
                    f_score = tentative_g + heuristic(neighbor, goal)
                    heapq.heappush(open_set, (f_score, neighbor))
                    came_from[neighbor] = current
    return None

# 🧪 Sample Grid and Execution
grid = [
    [0, 0, 0, 0],
    [1, 1, 0, 1],
    [0, 0, 0, 0],
    [0, 1, 1, 0]
]

start = (0, 0)
goal = (3, 3)

path = astar(grid, start, goal)
print("Shortest Path:", path)

Shortest Path: [(0, 0), (0, 1), (0, 2), (1, 2), (2, 2), (2, 3), (3, 3)]
